package com.davidecavestro.timekeeper.report;

import com.ost.timekeeper.util.*;
import java.awt.BorderLayout;
import java.io.InputStream;

import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.*;


/**
 * Visualizzatore report.
 * @author davide
 */
public final class ReportViewer extends javax.swing.JFrame {
	
	
	/**
	 *
	 */
	private JRViewer viewer = null;
	
	
	/** Costruttore. */
	public ReportViewer (
	String sourceFile,
	boolean isXMLFile
	) throws JRException {
		
		initComponents ();
		
		this.viewer = new JRViewer (sourceFile, isXMLFile);
		this.pnlMain.add (this.viewer, BorderLayout.CENTER);
	}
	
	
	/** Costruttore. */
	public ReportViewer (
	InputStream is,
	boolean isXMLFile
	) throws JRException {
		
		initComponents ();
		
		this.viewer = new JRViewer (is, isXMLFile);
		this.pnlMain.add (this.viewer, BorderLayout.CENTER);
	}
	
	
	/** Costruttore. */
	public ReportViewer (
	JasperPrint jasperPrint
	) throws JRException {
		
		initComponents ();
		
		this.viewer = new JRViewer (jasperPrint);
		this.pnlMain.add (this.viewer, BorderLayout.CENTER);
	}
	
	
	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	private void initComponents () {
		pnlMain = new javax.swing.JPanel ();
		
		setTitle (ResourceSupplier.getString (ResourceClass.UI, "controls", "report.viewer"));
		setIconImage (new javax.swing.ImageIcon (getClass ().getResource ("/net/sf/jasperreports/view/images/jricon.GIF")).getImage ());
		
		pnlMain.setLayout (new java.awt.BorderLayout ());
		
		getContentPane ().add (pnlMain, java.awt.BorderLayout.CENTER);
		
		pack ();
		java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit ().getScreenSize ();
		setSize (new java.awt.Dimension (750, 550));
		setLocation ((screenSize.width-750)/2,(screenSize.height-550)/2);
	}
	
	/**
	 *
	 */
	public static void viewReport (
	String sourceFile,
	boolean isXMLFile
	) throws JRException {
		JasperViewer jasperViewer =
		new JasperViewer (
		sourceFile,
		isXMLFile,
		false
		);
		jasperViewer.show ();
	}
	
	/**
	 *
	 */
	public static void viewReport (
	InputStream is,
	boolean isXMLFile
	) throws JRException {
		JasperViewer jasperViewer =
		new JasperViewer (
		is,
		isXMLFile,
		false
		);
		jasperViewer.show ();
	}
	
	/**
	 *
	 */
	public static void viewReport (
	JasperPrint jasperPrint
	) throws JRException {
		JasperViewer jasperViewer =
		new JasperViewer (
		jasperPrint,
		false
		);
		jasperViewer.show ();
	}
	
	
	// Variables declaration - do not modify
	private javax.swing.JPanel pnlMain;
	// End of variables declaration
	
}
