<?xml version="1.0" encoding="ISO-8859-1" standalone="no"?>
<!--generated by JHelpDev Version: 0.27-03/03/04, see jhelpdev.sourceforge.org--><!DOCTYPE helpset PUBLIC "-//Sun Microsystems Inc.//DTD JavaHelp HelpSet Version 2.0//EN" "http://java.sun.com/products/javahelp/helpset_2_0.dtd">

<helpset version="1.0">

    <title>JTTSlite Help System</title>

    <maps>
	<homeID>top</homeID>
    </maps>

    <!−− views −−>
    <view>
	<name>TOC</name>
	<label>Tabella dei Contenuti</label>
	<type>javax.help.TOCView</type>
    </view>
    <view>
	<name>Index</name>
	<label>Indice</label>
	<type>javax.help.IndexView</type>
    </view>
    <view>
	<name>Search</name>
	<label>Cerca</label>
	<type>javax.help.SearchView</type>
    </view>
    <view>
	<name>Favorites</name>
	<label>Favorites</label>
	<type>javax.help.FavoritesView</type>
    </view>

    <subhelpset location="it/JTTSlite.hs" />
</helpset>
