/*
 * LogConsole.java
 *
 * Created on April 18, 2006, 2:32 PM
 */

package net.sf.jttslite.gui;

import net.sf.jttslite.ApplicationContext;
import javax.swing.text.Document;
import net.sf.jttslite.prefs.PersistentComponent;

/**
 * Console di log.
 *
 * @author  davide
 */
public class LogConsole extends javax.swing.JFrame implements PersistentComponent {
	
	private final ApplicationContext _context;
	/** Costruttore. */
	public LogConsole (ApplicationContext context) {
		super (/*context.getWindowManager ().getMainWindow ()*/);
		this._context = context;
		
		initComponents ();
		
		setLocationRelativeTo (null);
	}
	
	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jScrollPane1 = new javax.swing.JScrollPane();
        logPanel = new javax.swing.JTextPane();

        getContentPane().setLayout(new java.awt.GridBagLayout());

        logPanel.setBackground(new java.awt.Color(0, 0, 0));
        logPanel.setEditable(false);
        logPanel.setForeground(new java.awt.Color(255, 255, 255));
        logPanel.setCaretColor(new java.awt.Color(255, 255, 255));
        logPanel.setPreferredSize(new java.awt.Dimension(480, 200));
        jScrollPane1.setViewportView(logPanel);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        getContentPane().add(jScrollPane1, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents
	
	/**
	 * Inizializza la finestra sul documento specificato.
	 *
	 * @param logDocument il documento contenente le informazioni di log.
	 */	
	public void init (final Document logDocument){
		logPanel.setDocument (logDocument);
		setTitle (prepareTitle (_context));
	}
	
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextPane logPanel;
    // End of variables declaration//GEN-END:variables
	
	private String prepareTitle (ApplicationContext context){
		final StringBuilder sb = new StringBuilder ();
		sb.append (context.getApplicationData ().getApplicationExternalName ()).append (" - Log console");
		return sb.toString ();
	}

	public String getPersistenceKey () {
		return "logconsole";
	}

	public void makePersistent () {
		_context.getPreferenceManager ().getGuiPreferences ().makeBoundsPersistent (getPersistenceKey (), this);
	}

	public boolean restorePersistent () {
		return _context.getPreferenceManager ().getGuiPreferences ().restorePersistentBounds (getPersistenceKey (), this);
	}
}
